export default {
  SIGNIN_EMAIL: 'SIGNIN_EMAIL',
  SIGNIN_GOOGLE: 'SIGNIN_GOOGLE',
  SET_USER: 'SET_USER',
  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  SIGN_OUT: 'SIGN_OUT',
  REGISTER_USER: 'REGISTER_USER'
}